#shiro setting
shiroConfig.sessionIdCookie:
  name: clid
  domain: a.sh.centanet.com
  path: /trade-mobile
shiroConfig.sessionUserCookie:
  name: suid
  domain: a.sh.centanet.com
  path: /
shiroConfig.shiroFilter:
  loginUrl: http://sso.sh.centaline.com.cn/aist-sso-web/login?service=http://a.sh.centanet.com/partner/cas
  successUrl: /
  unauthorizedUrl: http://a.sh.centanet.com/partner
  filterChainDefinitionMap:
    /casFailure.jsp: anon
    /cas: cas
    /html/**: anon
    /remote/**: anon
    /mobile/**: anon
    /test/**: anon
    /momedia/**: anon
    /webservices/**: anon
    /userorg/org/findOrgZTreeListByAdminOrg.json: anon
    /anon/**: anon
    /login: authc
    /logout: logout
    /api/**: anon
    /api-docs: anon
    /rest/**: anon
    /**: anon
    /authenticated: authc
    /weixin/**: weiXinUser
    /tweixin/**: weiXinUser
    /weixinAuth: weixinAuth
    /restful/login**: restfulAuth
    /restful/refreshToken**: restfulAuth
    /**: customUser
  filters:
    weiXinUser:
      corpId: wx7b47806a86fe27db
      corpsecret: du8lu_E-kC1zyvofc4CPw53tNFdtF4AnbBXRJ9l9Z3d316FzsLRl1WB2Yqw4VVzB
shiroConfig.logouFilter:
  redirectUrl: http://tradesso.centaline.com.cn/aist-sso-web/login?service=http://a.sh.centanet.com/partner/cas
casRealm:
  casService: a.sh.centanet.com/partner/cas
  casServerUrlPrefix: http://tradesso.centaline.com.cn/aist-sso-web
# Server settings (ServerProperties Spring boot)
server:
  port: 8095
  #address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /trade-api
#数据源
dataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://${systemProperties['dbhost']}:1433;databaseName=sctrans_prd;applicationName=trade-mobile
  username: ${systemProperties['dbuid']}
  password: ${systemProperties['dbpass']}
  maxActive: 250
  initialSize: 50
  filters: stat
#数据源
readOnlyDataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://${systemProperties['dbhost']}:1433;databaseName=sctrans_prd;applicationName=trade-mobile
  #;ApplicationIntent=ReadOnly
  username: ${systemProperties['dbuid']}
  password: ${systemProperties['dbpass']}
  maxActive: 350
  initialSize: 50
  filters: stat
#微信相关
weiXin.number:
  corpId: wx7b47806a86fe27db
  corpsecret: du8lu_E-kC1zyvofc4CPw53tNFdtF4AnbBXRJ9l9Z3d316FzsLRl1WB2Yqw4VVzB
#Mybatis
mybatis:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.centaline.parportal.**.repository
  configLocation: classpath:/mapper/mappers.xml

## redis配置
redis:
  cluster:
    nodes: 'redis01:6379,redis02:6380,redis03:6381,redis04:6379,redis05:6380,redis06:6381'
    max-redirects: 5
  maxIdle: 100
  maxTotal: 600

  # 案件消息队列开关 自动启动流程或发送发送CCAI秘书调整案件完成消息开关 true启动 false忽略消息队列信息
trade.casemq.enable: true
  #定义获取密钥的header name
trade.apikey.headerName: secretKey