#shiro setting
shiroConfig.sessionIdCookie:
  name: clid
  domain: partner.centaline.com
  path: /trade-api
shiroConfig.sessionUserCookie:
  name: suid
  domain: centaline.com
  path: /
shiroConfig.shiroFilter:
  loginUrl: http://sso.centaline.com:8080/aist-sso-web/login?service=http://partner.centaline.com:8080/partner/cas
  successUrl: /
  unauthorizedUrl: http://partner.centaline.com:8080/partner/
  filterChainDefinitionMap:
    /casFailure.jsp: anon
    /cas: cas
    /html/**: anon
    /remote/**: anon
    /mobile/**: anon
    /test/**: anon
    /momedia/**: anon
    /webservices/**: anon
    /userorg/org/findOrgZTreeListByAdminOrg.json: anon
    /anon/**: anon
    /login: authc
    /logout: logout
    #TODO 后面加入自定义的过滤器 进行权限校验
    /api/**: anon
    /api-docs: anon
    /rest/**: anon
    /**: anon
    /authenticated: authc
    /weixin/**: weiXinUser
    /tweixin/**: weiXinUser
    /weixinAuth: weixinAuth
    /restful/login**: restfulAuth
    /restful/refreshToken**: restfulAuth
    #/**: customUser
  filters:
    weiXinUser:
      corpId: wx7b47806a86fe27db
      corpsecret: du8lu_E-kC1zyvofc4CPw53tNFdtF4AnbBXRJ9l9Z3d316FzsLRl1WB2Yqw4VVzB
shiroConfig.logouFilter:
  redirectUrl: http://sso.centaline.com:8080/aist-sso-web/logout?service=http://partner.centaline.com:8080/partner/cas
casRealm:
  casService: http://partner.centaline.com:8080/partner/cas
  casServerUrlPrefix: http://sso.centaline.com:8080/aist-sso-web
# Server settings (ServerProperties)
server:
  port: 8083
  #address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /trade-api
#数据源
dataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://10.1.30.100:1433;databaseName=sctrans_dev
  username: dev
  password: dev@123
  maxActive: 10
  initialSize: 5
  filters: stat
#数据源
readOnlyDataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://10.1.30.100:1433;databaseName=sctrans_dev
  username: dev
  password: dev@123
  maxActive: 11
  initialSize: 6
  filters: stat
#Mybatis
mybatis: 
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.centaline.trans.**.repository
  configLocation: classpath:/mapper/mappers.xml
## redis配置
redis:
  cluster:
    nodes: '10.1.30.104:1000,10.1.30.104:2010,10.1.30.104:1010,10.1.30.104:3000,10.1.30.104:2000,10.1.30.104:3010'
    max-redirects: 5
  maxIdle: 100
  maxTotal: 600

#swagger
swagger:
  #不配置的话 会导致部署到服务器上 自动生成本机的host无法进行代理,配置需要加上端口
  host: localhost:8083