#shiro setting
shiroConfig.sessionIdCookie:
  name: clid
  domain: agent.centaline.com
  path: /agent
shiroConfig.sessionUserCookie:
  name: suid
  domain: centaline.com
  path: /
shiroConfig.shiroFilter:
  loginUrl: http://sso.centaline.com:8080/aist-sso-web/login?service=http://agent.centaline.com:8080/agent/cas
  successUrl: /
  unauthorizedUrl: http://agent.centaline.com:8080/agent/
  filterChainDefinitionMap:
    /casFailure.jsp: anon
    /cas: cas
    /remote/**: anon
    /mobile/**: anon
    /momedia/**: anon
    /webservices/**: anon
    /userorg/org/findOrgZTreeListByAdminOrg.json: anon
    /anon/**: anon
    /login: authc
    /logout: logout
    /api/**: anon
    /rest/**: anon
    /authenticated: authc
    /weixin/**: weiXinUser
    /tweixin/**: weiXinUser
    /weixinAuth: weixinAuth
    /**: user
  filters:
    weiXinUser:
      corpId: wx7b47806a86fe27db
      corpsecret: du8lu_E-kC1zyvofc4CPw53tNFdtF4AnbBXRJ9l9Z3d316FzsLRl1WB2Yqw4VVzB
shiroConfig.logouFilter:
  redirectUrl: http://sso.centaline.com:8080/aist-sso-web/logout?service=http://agent.centaline.com:8080/agent/cas
casRealm:
  casService: http://agent.centaline.com:8080/agent/cas
  casServerUrlPrefix: http://sso.centaline.com:8080/aist-sso-web
# Server settings (ServerProperties)
server:
  port: 8080
 # address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /agent
#数据源
dataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://10.4.19.22:1433;databaseName=sctrans_dev
  username: dev
  password: dev.good
  maxActive: 10
  initialSize: 5
  filters: stat
#数据源
readOnlyDataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://10.4.19.22:1433;databaseName=sctrans_dev
  username: dev
  password: dev.good
  maxActive: 11
  initialSize: 6
  filters: stat
#redis缓存
redisSetting:
  master:
    master1
  sentinels:
  - host: 10.4.19.212
    port: 26379
  - host: 10.4.19.212
    port: 26380
redisPoolConfig:
  minIdle:200
  maxIdle:20
  maxTotal:5
  maxWaitMillis:3000
  testOnBorrow:true
#微信相关
weiXin.number:
  corpId: wx7b47806a86fe27db
  corpsecret: du8lu_E-kC1zyvofc4CPw53tNFdtF4AnbBXRJ9l9Z3d316FzsLRl1WB2Yqw4VVzB

     