 # Dockerfile for Swagger Editor
# Updated 20170413

FROM docker.aist.io/aist_swagger

MAINTAINER Lin Jiarong <linjr@aisthink.com>
ADD swagger/ /opt/swagger
EXPOSE 80
CMD ["swagger","project","edit","-p","80"]
