 # Dockerfile for Swagger Editor
# Updated 20170413

FROM node

MAINTAINER Lin Jiarong <linjr@aisthink.com>
RUN npm install -g swagger && \
    cd /opt && \
    mkdir swagger &&\
    cd swagger
WORKDIR /opt/swagger
ADD swagger/* /opt/swagger
EXPOSE 80
CMD ["swagger project edit -p 80"]
