INSERT INTO ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, TENANT_ID_, DEPLOY_TIME_) 
SELECT ID_, NAME_, CATEGORY_, TENANT_ID_, DEPLOY_TIME_ FROM [10.28.19.219].activiti_dev.dbo.ACT_RE_DEPLOYMENT where ID_ =1030005 and not exists(select 1 from ACT_RE_DEPLOYMENT where ID_ =1030005);

INSERT INTO ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_) 
SELECT ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_ FROM [10.28.19.219].activiti_dev.dbo.ACT_RE_PROCDEF where DEPLOYMENT_ID_=1030005 and not exists(select 1 from ACT_RE_PROCDEF WHERE DEPLOYMENT_ID_=1030005);

INSERT INTO ACT_GE_BYTEARRAY (ID_, REV_, NAME_, DEPLOYMENT_ID_, BYTES_, GENERATED_) 
SELECT ID_, REV_, NAME_, DEPLOYMENT_ID_, BYTES_, GENERATED_ FROM [10.28.19.219].activiti_dev.dbo.ACT_GE_BYTEARRAY where DEPLOYMENT_ID_ = 1030005 and not exists(select 1 from ACT_GE_BYTEARRAY where DEPLOYMENT_ID_=1030005);

ALTER TABLE sctrans.T_TO_ELOAN_CASE ADD LOANER_CONF_TIME datetime ;

CREATE TABLE [sctrans].[T_TO_ELOAN_LOANER] (
[PKID] bigint NOT NULL IDENTITY(1,1) ,
[ELOAN_CODE] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[CASE_CODE] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[RECEIVE_CODE] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[CUST_NAME] nvarchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[CUST_PHONE] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[HOU_ADDRESS] varchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
[APPLY_TIME] datetime NULL ,
[APPLY_AMOUNT] decimal(18,2) NULL ,
[MONTH] int NULL ,
[FLOW_STATUS] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[LOANER_STATUS] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[LOANER_DESC] varchar(500) COLLATE Chinese_PRC_CI_AS NULL ,
[SEND_ID] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[SEND_NAME] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[RECEIVE_TIME] datetime NULL ,
[SEND_TIME] datetime NULL ,
[RECEIVE_ID] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[RECEIVE_NAME] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[REJECT_ID] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[REJECT_NAME] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[REJECT_TIME] datetime NULL ,
[CANCLE_ID] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[CANCLE_NAME] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[CANCLE_TIME] datetime NULL DEFAULT '' ,
[CREATE_TIME] datetime NULL ,
[CREATE_BY] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[UPDATE_TIME] datetime NULL ,
[UPDATE_BY] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[LOANER_ID] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
[LOANER_NAME] varchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
[LOANER_ORG_ID] varchar(32) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK_T_TO_ELOAN_LOANER] PRIMARY KEY ([PKID])
)