CREATE TABLE [sctrans].[T_RPT_CASE_BASE_INFO](
	[PKID] [bigint] IDENTITY(1,1) NOT NULL,
	[CASE_CODE] [varchar](32) NULL,
	[LOAN_REQ] [char](2) NULL,
	[CASE_STATUS] [varchar](32) NULL,
	[CASE_PROPERTY] [varchar](32) NULL,
	[DISTRICT_ID] [varchar](32) NULL,
	[TEAM_ID] [varchar](32) NULL,
	[RECEIVED_TIME] [datetime] NULL,
	[RECEIVED_USER] [varchar](32) NULL,
	[RECEIVED_TEAM_ID] [varchar](32) NULL,
	[RECEIVED_DISTRICT_ID] [varchar](32) NULL,
	[SIGN_TIME] [datetime] NULL,
	[SIGN_USER] [varchar](32) NULL,
	[SIGN_TEAM_ID] [varchar](32) NULL,
	[SIGN_DISTRICT_ID] [varchar](32) NULL,
	[HOUSE_TRANFER_TIME] [datetime] NULL,
	[HOUSE_TRANFER_USER] [varchar](32) NULL,
	[HOUSE_TRANFER_TEAM_ID] [varchar](32) NULL,
	[HOUSE_TRANFER_DISTRICT_ID] [varchar](32) NULL,
	[HOURSE_TRANSFER_APPROVE_DATE] [datetime] NULL,
	[HOURSE_TRANSFER_AGREE_STATUS] [char](2) NULL,
	[CLOSE_TIME] [datetime] NULL,
	[CLOSE_USER] [varchar](32) NULL,
	[CLOSE_TEAM_ID] [varchar](32) NULL,
	[CLOSE_DISTRICT_ID] [varchar](32) NULL,
	[MORTGAGE_LOAN_TYPE] [varchar](32) NULL,
	[MORTGAGET_TOTAL_AMOUNT] [decimal](18, 2) NULL,
	[MORTGAGET_COM_AMOUNT] [decimal](18, 2) NULL,
	[MORTGAGET_PRF_AMOUNT] [decimal](18, 2) NULL,
	[MORTGAGET_FIN_ORG_CODE] [varchar](32) NULL,
	[MORTGAGET_IS_TMP_BANK] [char](2) NULL,
	[IS_LOSE] [char](2) NULL,
	[CREATE_BY] [varchar](32) NULL,
	[CREATE_TIME] [datetime] NULL,
	[UPDATE_TIME] [datetime] NULL,
	[UPDATE_BY] [varchar](32) NULL
) ON [PRIMARY]



